### ISSUE TITLE
Looks Like Summarize IP's Portal is not working properly

### ISSUE THREAD

**Issue by allamnaveen123** [wand3rlust/Fairth#1]
Getting below error 

{
  "code": "error.msg.unknownError",
  "message": "Unknown error",
  "status": 500,
  "errors": []
}                                                                                                                                                                    ✓

I know there is no bug in the code, I Just appreciated please let me know if i am missing something.

**Comment by allamnaveen123** [comment]
@wand3rlust Can you please help me here, I am thinking to utilize your solution for deeper understanding

**Comment by wand3rlust** [comment]
@allamnaveen123, I have just tested and its working.

Please let me know which OS & Python version did you use?

**Comment by allamnaveen123** [comment]
![Screenshot 2024-07-30 093317](https://github.com/user-attachments/assets/e3e723ca-bce8-48a0-bce0-ca71531246e1)
@wand3rlust  on Web console only it is not working please refer to the attached screenshot

**Comment by wand3rlust** [comment]
@allamnaveen123 the issue could be on their end or it could be the browser settings/addons, etc.

**Comment by allamnaveen123** [comment]
@wand3rlust Thank you for reverting back, even yourself facing same issue what Iam facing right now

**Comment by wand3rlust** [comment]
@allamnaveen123 yes, I did encountered similar case while validiating your issue.

That said, am closing this issue for now as it's not relevant to the tool. Feel free to reach out to the IPInfo team and let them know.
